Repository wecode-bootcamp-korea/35-backend-westagram-1, pull requests merged in 2022-07, with the labels that each got.

#3 [35기 음정민] Mission 1 : Django 초기 세팅
  students/jungmin/westagram/.gitignore
  students/jungmin/westagram/manage.py
  students/jungmin/westagram/requirements.txt
  students/jungmin/westagram/westagram/__init__.py
  students/jungmin/westagram/westagram/asgi.py
  students/jungmin/westagram/westagram/settings.py
  students/jungmin/westagram/westagram/urls.py
  students/jungmin/westagram/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#2 [35기 김동규] Mission 1 : Django 초기 세팅
  students/donggyu/.gitignore
  students/donggyu/manage.py
  students/donggyu/requirements.txt
  students/donggyu/westagram/__init__.py
  students/donggyu/westagram/asgi.py
  students/donggyu/westagram/settings.py
  students/donggyu/westagram/urls.py
  students/donggyu/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#5 [35기 조민지] Mission 1: Django 초기 세팅
  students/minji/.gitignore
  students/minji/manage.py
  students/minji/requirements.txt
  students/minji/westagram/__init__.py
  students/minji/westagram/asgi.py
  students/minji/westagram/settings.py
  students/minji/westagram/urls.py
  students/minji/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#4 [35기 홍현진] Mission1 : Django 초기 세팅
  students/hyeonjin/.gitignore
  students/hyeonjin/manage.py
  students/hyeonjin/requirements.txt
  students/hyeonjin/westagram/__init__.py
  students/hyeonjin/westagram/asgi.py
  students/hyeonjin/westagram/settings.py
  students/hyeonjin/westagram/urls.py
  students/hyeonjin/westagram/wsgi.py
Labels: 멘토 리뷰 요청

#6 [음정민] Mission 2: 모델링
  students/jungmin/westagram/users/__init__.py
  students/jungmin/westagram/users/admin.py
  students/jungmin/westagram/users/apps.py
  students/jungmin/westagram/users/migrations/0001_initial.py
  students/jungmin/westagram/users/migrations/__init__.py
  students/jungmin/westagram/users/models.py
  students/jungmin/westagram/users/tests.py
  students/jungmin/westagram/users/views.py
  students/jungmin/westagram/westagram/settings.py
Labels: 완료

#8 [조민지] Mission 2: 모델링
  students/minji/users/__init__.py
  students/minji/users/admin.py
  students/minji/users/apps.py
  students/minji/users/migrations/0001_initial.py
  students/minji/users/migrations/__init__.py
  students/minji/users/models.py
  students/minji/users/tests.py
  students/minji/users/views.py
  students/minji/westagram/settings.py
Labels: 완료

#7 [김동규] Mission 2: 모델링
  students/donggyu/users/__init__.py
  students/donggyu/users/admin.py
  students/donggyu/users/apps.py
  students/donggyu/users/migrations/0001_initial.py
  students/donggyu/users/migrations/0002_alter_user_email_alter_user_table.py
  students/donggyu/users/migrations/0003_user_created_at_user_updated_at_alter_user_email_and_more.py
  students/donggyu/users/migrations/__init__.py
  students/donggyu/users/models.py
  students/donggyu/users/tests.py
  students/donggyu/users/views.py
  students/donggyu/westagram/settings.py
Labels: 멘토 리뷰 요청

#9 [35기 홍현진] Mission 2 : 모델링
  students/hyeonjin/users/__init__.py
  students/hyeonjin/users/admin.py
  students/hyeonjin/users/apps.py
  students/hyeonjin/users/migrations/0001_initial.py
  students/hyeonjin/users/migrations/0002_alter_user_table.py
  students/hyeonjin/users/migrations/__init__.py
  students/hyeonjin/users/models.py
  students/hyeonjin/users/tests.py
  students/hyeonjin/users/views.py
  students/hyeonjin/westagram/settings.py
Labels: 멘토 리뷰 요청

#11 [음정민] Mission 3: 회원가입 기능 구현
  students/jungmin/westagram/users/migrations/0002_alter_user_email.py
  students/jungmin/westagram/users/models.py
  students/jungmin/westagram/users/urls.py
  students/jungmin/westagram/users/views.py
  students/jungmin/westagram/westagram/urls.py
Labels: 멘토 리뷰 요청

#10 [홍현진] Mission 3: 회원가입 기능 구현
  students/hyeonjin/users/migrations/0001_initial.py
  students/hyeonjin/users/models.py
  students/hyeonjin/users/urls.py
  students/hyeonjin/users/views.py
  students/hyeonjin/westagram/urls.py
Labels: 멘토 리뷰 요청

#12 [김동규] Mission 3: 회원가입 기능 구현
  students/donggyu/users/models.py
  students/donggyu/users/urls.py
  students/donggyu/users/views.py
  students/donggyu/westagram/urls.py
Labels: 완료

#13 [조민지] Mission 3: 회원가입 기능 구현
  students/minji/users/apps.py
  students/minji/users/urls.py
  students/minji/users/views.py
  students/minji/westagram/urls.py
Labels: 멘토 리뷰 요청

#17 [김동규] Mission 4: 로그인 기능 구현
  students/donggyu/users/urls.py
  students/donggyu/users/views.py
Labels: 멘토 리뷰 요청

#14 [음정민] Mission 4: 로그인 기능 구현
  students/jungmin/westagram/users/urls.py
  students/jungmin/westagram/users/views.py
Labels: 멘토 리뷰 요청

#15 [홍현진] Mission 4: 로그인 기능 구현
  students/hyeonjin/users/urls.py
  students/hyeonjin/users/views.py
Labels: 멘토 리뷰 요청

#16 [조민지] Mission 4: 로그인 기능 구현
  students/minji/users/urls.py
  students/minji/users/views.py
Labels: 멘토 리뷰 요청

#18 [음정민] Mission 5: 회원가입 비밀번호 암호화 적용
  students/jungmin/westagram/users/views.py
Labels: 멘토 리뷰 요청

#20 [홍현진] Mission 5: 회원가입 비밀번호 암호화 적용
  students/hyeonjin/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#22 [조민지] Mission 5: 회원가입 비밀번호 암호화 적용
  students/minji/users/views.py
Labels: 멘토 리뷰 요청

#19 [김동규] Mission 5: 회원가입 비밀번호 암호화 적용
  students/donggyu/users/views.py
Labels: 멘토 리뷰 요청

#23 [음정민] Mission 6: 로그인 JWT 발급
  students/jungmin/westagram/users/views.py
  students/jungmin/westagram/westagram/settings.py
Labels: 멘토 리뷰 요청

#21 [홍현진] Mission 6: 로그인 JWT 발급
  students/hyeonjin/users/views.py
  students/hyeonjin/westagram/settings.py
Labels: 멘토 리뷰 요청

#24 [김동규] Mission 6: 로그인 JWT 발급
  students/donggyu/users/views.py
  students/donggyu/westagram/settings.py
Labels: 멘토 리뷰 요청

#25 [조민지] Mission 6: 로그인 JWT 발급
  students/minji/users/views.py
  students/minji/westagram/settings.py
Labels: 멘토 리뷰 요청
